Ombi-app/Ombi

PlexRequests.UI/Bootstrapper.cs
PlexRequests.UI/Helpers/ValidationHelper.cs
PlexRequests.UI/Modules/AdminModule.cs
PlexRequests.UI/PlexRequests.UI.csproj
PlexRequests.UI/Program.cs
PlexRequests.UI/Validators/CouchPotatoValidator.cs
PlexRequests.UI/Validators/PlexValidator.cs
PlexRequests.UI/Validators/SonarrValidator.cs
PlexRequests.UI/Views/Admin/CouchPotato.cshtml
PlexRequests.UI/Views/Admin/Plex.cshtml
PlexRequests.UI/Views/Admin/Settings.cshtml
PlexRequests.UI/Views/Admin/Sonarr.cshtml
PlexRequests.UI/packages.config
README.md
appveyor.yml

Fixed an issue when accessing remotely

Update to 1.2.1

---

PlexRequests.UI/Modules/SearchModule.cs
PlexRequests.UI/Resources/UI.Designer.cs
PlexRequests.UI/Resources/UI.da.resx
PlexRequests.UI/Resources/UI.de.resx
PlexRequests.UI/Resources/UI.es.resx
PlexRequests.UI/Resources/UI.fr.resx
PlexRequests.UI/Resources/UI.it.resx
PlexRequests.UI/Resources/UI.nl.resx
PlexRequests.UI/Resources/UI.pt.resx
PlexRequests.UI/Resources/UI.resx
PlexRequests.UI/Views/Shared/_Layout.cshtml

Added French language into the navigation bar

Fixed the bug where we were auto approving everything.

---

PlexRequests.UI/Views/Search/Index.cshtml

Updated view to show new lables depending on state

f#552: Re-design lables

---

PlexRequests.UI/Resources/UI.resx
PlexRequests.UI/Resources/UI1.Designer.cs
PlexRequests.UI/Views/Requests/Index.cshtml
PlexRequests.UI/Views/Search/Index.cshtml

Added new lables to requests, moved some strings into resx files

s582: admin improvements part 2

---

.travis.yml

Hopefully fix travis builds by changing the solution name in .travis.yml

Change solution name in travis

---

Ombi.Store/Repository/PlexUserRepository.cs

Plex Username Case Sensitivity Fix

---

Ombi.UI/Content/search.js
Ombi.UI/Models/SearchTvShowViewModel.cs
Ombi.UI/Modules/SearchModule.cs
Ombi.UI/Views/Search/Index.cshtml

Fix issue described in #742 - lightly tested and seems to work ok.

Fix Issue #742

---

Ombi.UI/Views/Integration/Radarr.cshtml

Fixed references to TV, instead of Movies.

Fix Radarr labels

---

Ombi.Core/HeadphonesSender.cs
Ombi.Store/RequestedModel.cs
Ombi.UI/Modules/SearchModule.cs

Fix Headphones album search integration.

---

Ombi.Services/Jobs/RecentlyAddedNewsletter/RecentlyAddedNewsletter.cs
Ombi.Services/Notification/EmailMessageNotification.cs
Ombi.Services/Notification/NotificationService.cs
Ombi.UI/Modules/Admin/AdminModule.cs
Ombi.UI/Modules/Admin/CustomizationModule.cs

Also VS2017 without Update 1 complains about every cshtml file until updated. Just a FYI incase you updated and see the issue.

Quick fix for email false positive message. ISSUE: #1286

---

Ombi/Ombi/wwwroot/app/config.ts

With the new bundling config stuff this is no longer needed

Remove unneeded bundle config

---

Ombi.UI/Resources/UI.sv.resx

One misspelled word in the main menu. Önsningar -> Önskningar
And changed Problem to Önska according to the issue: #1410

Changed two words that was wrong

---

Ombi.UI/Resources/UI.it.resx

Fixed Msuica to Musica in Italian language

Minor fix to Italian language

---

src/Ombi/ClientApp/app/login/login.component.html

By default, uses logo.png rather than ms-icon-150x150.png

Fix logo on login page.

---

src/Ombi/ClientApp/app/login/login.component.scss

Automatically scales images larger than the containing div down to the size of the div.

Auto-scale large images down to container size

---

src/Ombi.Api.Radarr/Models/MovieResponse.cs

Fixes an issue with Movie caching not working on develop branch of Radarr

---

src/Ombi.Core/Engine/TvRequestEngine.cs

Hey, first time doing anything on GitHub other than using it for my own code.
Hope I did this right.

Episodes in requests are now in order #1597

---

README.md

The proges of the gif:
1. Landing Page
2. Login
3. Search and Request 
3.a Movie - Avatar showing both request and the available function (Link to Plex)
3.b Series - Star Trek showing the different request options - all, first and last season
3. Show Requests for both movie and series

New preview gif for Ombi V3 README

---

src/Ombi/package-lock.json
src/Ombi/package.json

https://github.com/ReactiveX/rxjs/issues/3151#issuecomment-348730503

fix startup config error

---

src/Ombi/ClientApp/app/requests/movierequests.component.html

Let non-admin users report an issue on a requested item.
I just moved <div class="dropdown" *ngIf="issueCategories && issuesEnabled"> outside of <div *ngIf="isAdmin">

Fix non-admin issues dropdown

---

src/Ombi.Notifications.Templates/Templates/BasicTemplate.html
src/Ombi.Notifications/Agents/EmailNotification.cs
src/Ombi.Notifications/GenericEmailProvider.cs

As promised. It's literally the first C# I've coded and I have no idea what I'm doing :').
It works, but it might not be best practice. So feel free to make changes as necessary.
Just look at that sweet 10/10
http://www.mail-tester.com/web-47ta3

Enable Multi MIME and add alt tags to images

---

src/Ombi/ClientApp/app/landingpage/landingpage.component.html
src/Ombi/ClientApp/app/landingpage/landingpage.component.scss
src/Ombi/ClientApp/app/login/login.component.html
src/Ombi/ClientApp/app/login/login.component.scss
src/Ombi/ClientApp/app/login/resetpassword.component.html

Image now centered so it looks better in general, mostly on small devices though. img changed to div to avoid 1px gray border in chrome and safari.

Better login backgrounds!

---

src/Ombi/ClientApp/app/app.component.html

Change plus to list in menu

---

src/Ombi/ClientApp/app/usermanagement/usermanagement.component.html
src/Ombi/ClientApp/styles/base.scss

Now I'm not sure where you want the css for this, I just put it at the bottom of base.scss. Tell me if you want it somewhere else 👍 
https://vgy.me/Wec0UI.gif

Make user management table responsive

---

src/Ombi/ClientApp/styles/base.scss

At least until @leram84 comes along ;)

Fix mobile layout

---

src/Ombi.Notifications.Templates/EmailBasicTemplate.cs
src/Ombi.Notifications.Templates/Templates/BasicTemplate.html

E-Mails: Only add poster table row if img is set

---

src/Ombi.Settings/Settings/Models/CustomizationSettings.cs
src/Ombi/ClientApp/app/app.component.html
src/Ombi/ClientApp/app/interfaces/ISettings.ts
src/Ombi/ClientApp/app/settings/customization/customization.component.html
src/Ombi/wwwroot/translations/en.json

Brought back the custom donations navbar link.

Added custom donation url

---

src/Ombi/ClientApp/styles/base.scss

Shit that was easy (`overflow: visible;`), took be a bit to find it though.
Probably fixes #1913

Issue button fix

---

README.md

The fact that this button has another style really bothers me.

---

src/Ombi/Views/Shared/_Layout.cshtml

Add support for both IOS and Android.
Feathub: https://feathub.com/tidusjar/Ombi/+270

Add web-app-capable for IOS and Android

---

css/style.css
index.html

Fix mobile app links and add legal

---

src/Ombi/ClientApp/app/search/moviesearch.component.ts
src/Ombi/ClientApp/app/search/tvsearch.component.ts

Fix displaying year in issue dialog.

---

src/Ombi/ClientApp/app/requests/tvrequests.component.html

Hides Sonarr options on tv requests page if only 1 option available.

---

README.md

Update Readme for Lidarr

---

src/Ombi.Notifications.Templates/Templates/NewsletterTemplate.html
src/Ombi.Schedule/Jobs/Ombi/HtmlTemplateGenerator.cs

I have tested it on gmail.com and android 8 gmail app. Still needs some work for the iOS app but really close ! (https://github.com/tidusjar/Ombi/issues/2431)

Rewritten the whole newsletter template.

---

.github/ISSUE_TEMPLATE.md

I've made some minor grammatical and spelling changes to the issue template, to improve the clarity a bit. Feel free to merge or reject this PR at your leisure.
Comments, suggestions, and revisions welcome; leave a comment and I'll be happy to discuss. 
Have an excellent day!

Update ISSUE_TEMPLATE.md grammar

---

README.md

Fixing broken twitch url in readme file

---

src/Ombi/ClientApp/app/search/moviesearch.component.html
src/Ombi/ClientApp/app/search/music/musicsearch.component.html
src/Ombi/ClientApp/app/search/search.component.html
src/Ombi/ClientApp/app/search/search.component.scss
src/Ombi/ClientApp/app/search/tvsearch.component.html
src/Ombi/wwwroot/translations/en.json

I have many first time users who have no idea how to search because they could not find the search box

Placeholder Text for Search Boxes

---

src/Ombi/ClientApp/src/app/requests/movierequests.component.html

by moving the id="removeBtn" from the form tag to the button itself.

fix the UI a little

---

src/Ombi.Helpers.Tests/EmbyHelperTests.cs
src/Ombi.Helpers/EmbyHelper.cs

Hi ! 
I just saw the issue about emby and the wrong url, and see that @tidusjar solved it in the v4. and wondered if somebody will be interested to have it solved in the v3.
Then I just cherry-picked your commit :)

Fixed #3455

---

src/Ombi.Api.Emby/JellyfinApi.cs

Hello,
It's tested successfully in development mode, connection and manually caching the db.
Fix #3505

Fix jellyfin api call

---

.github/ISSUE_TEMPLATE/config.yml

Creating a GitHub config file to make sure users can't overwrite the issue template (creating an empty issue) and will be redirected to other places for posting feature requests or can choose alternative places for requesting help

Creating config.yml github file for feature request to the correct spot ;)

---

.github/ISSUE_TEMPLATE/config.yml

Fixing attempt, github doesn't load it :(

Fixing config.yml

---

src/Ombi.Store/Migrations/OmbiMySql/20200218230644_MobileDevices.cs

Deleted the collation of `UserID` to mirror the creation of ID in table aspnetusers

Changed the creation of MobileDevices to match aspnetusers

---

src/Ombi/ClientApp/src/app/settings/sonarr/sonarr.component.html

the `load` class isn't needed here

fixed sonarr settings buttons for good this time

---

src/Ombi/Controllers/V1/External/RadarrController.cs
src/Ombi/Controllers/V1/External/SonarrController.cs

Fixes the issue #3773 introduced in feature/v4 branch. 
I wasn't able to reproduce #3768 with the code that is currently in master branch.

Resolves endpoint conflict for swagger.

---

src/Ombi/ClientApp/src/app/my-nav/my-nav.component.ts

Disables feature suggestions for non-admin users.

---

src/Ombi/Controllers/V2/SystemController.cs

Sorts log files in decreasing order.

---

src/Ombi.Core/Engine/TvSearchEngine.cs
src/Ombi.Core/Engine/V2/MusicSearchEngineV2.cs
src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs
src/Ombi.Core/Helpers/TvShowRequestBuilder.cs
src/Ombi.Helpers.Tests/StringHelperTests.cs
src/Ombi.Helpers.Tests/UriHelperTests.cs
src/Ombi.Helpers/StringHelper.cs
src/Ombi.Mapping/Profiles/TvProfile.cs
src/Ombi.Mapping/Profiles/TvProfileV2.cs

Replaces scheme to https for all urls returned to client side.

---

src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.html
src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.scss

fixed up mobile CSS

---

src/Ombi/Views/Shared/_Layout.cshtml

Remove smart quotes from `og:site_name`.

Remove remaining smart quotes

---

src/Ombi/ClientApp/src/app/settings/sonarr/sonarr.component.ts

Replace "languge" with "Language"

Fix 'language' for sonarr v3

---

src/Ombi/ClientApp/src/app/landingpage/landingpage.component.ts

Just tweak the percentage a little to get a better rounding algorithm by replacing 20% by 19% and 80% by 79% as followed.
Result:

✨ CSS - Fix jagged edges on diagonal gradient overlay on landing page

---

src/Ombi/ClientApp/src/app/settings/massemail/massemail.component.html

Make button yellow instead of disappearing

Fix CSS of massemail submit button

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
CHANGELOG.md
README.md
src/Ombi.Helpers/PlexHelper.cs
src/Ombi/ClientApp/src/app/settings/about/about.component.html
src/Ombi/ClientApp/src/app/settings/update/update.component.html

update links in comments, issues, and readme

Org GitHub templating

---

README.md
src/Ombi.Notifications.Templates/Templates/BasicTemplate.html
src/Ombi.Notifications.Templates/Templates/NewsletterTemplate.html
src/Ombi/ClientApp/src/app/settings/about/about.component.html

Update links to releases in readme.md
Replaced all links to old repo with new repo in newsletters
Replaced all links to old repo with new repo in UI

Final link migration

---

src/Ombi/ClientApp/src/index.html

the icon is already here, just the <link rel=> tag missing
<link rel="apple-touch-icon" type="image/png" href="images/favicon/apple-touch-icon.png"/>

added icon for apple homescreen icon

---

src/Ombi.Notifications/BaseNotification.cs
src/Ombi.Notifications/NotificationMessageCurlys.cs

Resolves #4110.
Cleans up duplication in NotificationMessageCurlys class.

Capitalizes V for tv show notification type. Refactors NotificationMessageCurlys class.

---

src/Ombi/ClientApp/src/app/settings/couchpotato/couchpotato.component.html

Fixed issue with CouchPotato not loading profiles

---

src/Ombi.Core/Engine/MovieRequestEngine.cs

Fixed an issue where using sort on the movie request section wouldnt work

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts

Removes overwrite of requested field with undefined.

---

src/Ombi.Store/Ombi.Store.csproj
src/Ombi/Extensions/DatabaseExtensions.cs
src/Ombi/Ombi.csproj

Net6 mysql fixes

---

src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs
src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs

Follow up from this thread: https://github.com/Ombi-app/Ombi/pull/4388#discussion_r746070885

Display TV + movies on actor page in user language

---

src/Ombi/ClientApp/src/app/app.module.ts
src/Ombi/ClientApp/src/app/errors/not-found.component.ts
src/Ombi/ClientApp/src/app/issues/components/details/details.component.html
src/Ombi/ClientApp/src/app/localization/MatPaginatorI18n.ts
src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-information-panel/tv-information-panel.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-requests/tv-requests-panel.component.html
src/Ombi/ClientApp/src/app/media-details/media-details.component.scss
src/Ombi/ClientApp/src/app/requests/movierequests.component.html
src/Ombi/ClientApp/src/app/requests/music/musicrequests.component.html
src/Ombi/ClientApp/src/app/requests/tvrequests.component.html
src/Ombi/ClientApp/src/app/shared/chat-box/chat-box.component.html
src/Ombi/ClientApp/src/app/shared/components/genre-select/genre-select.component.html
src/Ombi/ClientApp/src/app/shared/components/keyword-search/keyword-search.component.html
src/Ombi/ClientApp/src/app/shared/components/watch-providers-select/watch-providers-select.component.html
src/Ombi/ClientApp/src/app/unsubscribe/components/confirm-component/unsubscribe-confirm.component.html
src/Ombi/wwwroot/translations/en.json

Yet another try at getting Ombi 100% localizable on the end user side.
Also tweaked some CSS to prevent buttons from being too small.
Before:
After:
I'm now pretty sure the only thing left is the newsletter body 🤞 but this requires handling localization on the backend, which is a lot of overhead for an inexperienced C# developer like myself, considering it's just for a couple of strings to translate. I'll pass on that one but would be happy to see it done someday.

Localization

---

src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-requests/tv-requests-panel.component.html

Detected in https://github.com/Ombi-app/Ombi/issues/4419

Fix incorrect text key reference RequestedByOn

---

src/Ombi.Core/Engine/TvRequestEngine.cs

Do not notify user upon auto approval of a TV show

---

src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.ts

Remove obsolete PreDb option from Radarr settings

---

tests/cypress/tests/search/search.spec.ts

I'm guessing the TV show info changed in Tmdb since that test was made.

Fix broken test

---

src/Ombi/ClientApp/src/app/my-nav/my-nav.component.html
src/Ombi/ClientApp/src/app/my-nav/my-nav.component.scss

I just went across [this issue](https://github.com/Ombi-app/Ombi/issues/3921) that seemed to be close to a one-liner to satisfy

Add link on logo text

---

src/Ombi.Api.Emby/Models/Media/EmbyProviderids.cs
src/Ombi.Api.Jellyfin/Models/Media/JellyfinProviderids.cs
src/Ombi.Api.Jellyfin/Ombi.Api.Jellyfin.csproj
src/Ombi.Api.MediaServer/Models/BaseProviderids.cs
src/Ombi.Api.MediaServer/Ombi.Api.MediaServer.csproj
src/Ombi.Schedule/Jobs/Emby/EmbyContentSync.cs
src/Ombi.Schedule/Jobs/Emby/EmbyEpisodeSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinContentSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinEpisodeSync.cs
src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs
src/Ombi.Schedule/Jobs/Plex/PlexEpisodeSync.cs

Add sanity checks upon media server sync

---

src/Ombi.Store/Entities/Requests/SeasonRequests.cs

Fixes Non requested series have a Pending Approval status #4553

Display blank status for episodes not requested

---

src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs
src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.html

Fixes the issue where denied movies would still show as "Pending Approval" on their details page.

Fix incorrect request status for denied movies

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.scss
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts
src/Ombi/ClientApp/src/app/interfaces/ISearchMovieResultV2.ts

Follow-up of https://github.com/Ombi-app/Ombi/pull/4575
Didn't notice then that the issue also occurred on the discover card.

Fix incorrect request status for denied movies in discover card

---

src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.ts
src/Ombi/ClientApp/src/app/requests-list/components/options/request-options.component.html
src/Ombi/ClientApp/src/app/requests-list/components/options/request-options.component.ts
src/Ombi/ClientApp/src/app/requests-list/components/requests-list.component.ts
src/Ombi/ClientApp/src/app/requests-list/models/UpdateType.ts
src/Ombi/wwwroot/translations/en.json

Add Deny option to requests list

---

src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/settings/radarr/components/radarr-form.component.ts
src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.html
src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.ts

fix(#4616): :bug: fixed mandatory fields

---

src/Ombi.Api.Plex/Models/Metadata.cs
src/Ombi/Controllers/V1/TokenController.cs
src/Ombi/Extensions/StartupExtensions.cs
src/Ombi/Ombi.csproj

- Supports Newtonsoft annotations, fixes incorrectly named properties and enum values in Swagger documentation
- Better documentation for POST token endpoint

Improve Swagger documentation

---

src/Ombi/ClientApp/src/app/app.module.ts
src/Ombi/ClientApp/src/app/components/image/image.component.html
src/Ombi/ClientApp/src/app/components/image/image.component.ts
src/Ombi/ClientApp/src/app/components/index.ts
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.html
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.scss
src/Ombi/ClientApp/src/app/discover/discover.module.ts
src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/shared/cast-carousel/cast-carousel.component.html
src/Ombi/ClientApp/src/app/media-details/components/shared/cast-carousel/cast-carousel.component.scss
src/Ombi/ClientApp/src/app/media-details/components/shared/media-poster/media-poster.component.html
src/Ombi/ClientApp/src/app/media-details/components/shared/top-banner/top-banner.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-information-panel/tv-information-panel.component.html
src/Ombi/ClientApp/src/app/media-details/media-details.module.ts

fix(discover): :bug: Created new Image component to handle 429's from TMDB (#4698) and fixed #4635

---

src/.idea/.idea.Ombi/.idea/contentModel.xml
src/Ombi/ClientApp/src/app/discover/components/actor/discover-actor.component.ts
src/Ombi/ClientApp/src/app/media-details/components/index.ts
src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.ts
src/Ombi/ClientApp/src/app/media-details/components/shared/cast-carousel/cast-carousel.component.html
src/Ombi/ClientApp/src/app/media-details/components/shared/crew-carousel/crew-carousel.component.html
src/Ombi/ClientApp/src/app/media-details/components/shared/crew-carousel/crew-carousel.component.scss
src/Ombi/ClientApp/src/app/media-details/components/shared/crew-carousel/crew-carousel.component.ts
src/Ombi/ClientApp/src/app/media-details/media-details.component.scss
src/Ombi/wwwroot/translations/en.json
src/Ombi/wwwroot/translations/fr.json

Add crew listing after cast listing, in order to show the director when available.
- The hyperlink is only on the photo, so when there's no photo, the person is not clickable. But this should probably be in another PR, I tried this: https://github.com/ketsapiwiq/Ombi/pull/1, but another solution is to implement a default photo as indicated in a TODO in the code
- If someone is confident enough to try to sort the Crew order so that the Director is at the beginning, I feel that would be very welcome.
Related:
- https://ombifeatures.featureupvote.com/suggestions/142857/search-by-directors
- https://ombifeatures.featureupvote.com/suggestions/320844/show-the-director-in-a-movie-page
- https://github.com/Ombi-app/Ombi/pull/1178

add crew on movie page

---

src/Ombi/ClientApp/src/app/components/detailed-card/detailed-card.component.ts
src/Ombi/ClientApp/src/app/components/image/image.component.ts

Fixes default image for recently requested items.

---

src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.ts

* Show request button when unaired episodes have not yet been requested (fullyAvailable and partlyAvailable == true)
* Since it's not possible to request episodes that may have never been requested but are available, updated the "allEpisodesRequested" to "allEpisodesRequestedOrAvailable"

Partially Available prevents further TV requests (#4768)

---

src/Ombi/ClientApp/src/app/app.module.ts
src/Ombi/ClientApp/src/app/login/login.component.ts
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.ts
src/Ombi/ClientApp/src/app/services/applications/sonarr.service.ts
src/Ombi/ClientApp/src/app/settings/sonarr/sonarr.component.html
src/Ombi/ClientApp/src/app/settings/sonarr/sonarr.component.ts
src/Ombi/ClientApp/src/app/shared/admin-request-dialog/admin-request-dialog.component.html
src/Ombi/ClientApp/src/app/shared/admin-request-dialog/admin-request-dialog.component.ts
src/Ombi/ClientApp/src/app/state/sonarr/index.ts
src/Ombi/ClientApp/src/app/state/sonarr/sonarr-initializer.ts
src/Ombi/ClientApp/src/app/state/sonarr/sonarr.actions.ts
src/Ombi/ClientApp/src/app/state/sonarr/sonarr.facade.ts
src/Ombi/ClientApp/src/app/state/sonarr/sonarr.selectors.ts
src/Ombi/ClientApp/src/app/state/sonarr/sonarr.state.ts
src/Ombi/ClientApp/src/app/state/sonarr/types.ts
src/Ombi/Controllers/V1/External/SonarrController.cs

Auto detect the sonarr version and adjust the UI depending on V3 or V4 (Lang profiles)

fix(sonarr): :bug: Sonarr V4 should work now

---

src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.html

- [Hide denied reason label if there is no value](https://github.com/Ombi-app/Ombi/commit/ce47cc3125bafbc36c88d1834e027a5555ca78e6)
Addresses this:
- [Movie would show as pending approval when denied](https://github.com/Ombi-app/Ombi/commit/b3191e471c401fa92efb83b4a593420cb7605889)
Addresses this:

Some minor tweaks to the movie info panel

---

src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.html
src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.ts

Fix denied movie shown as 'processing request' in details view

---

src/Ombi/ClientApp/src/app/components/detailed-card/detailed-card.component.html
src/Ombi/ClientApp/src/app/components/detailed-card/detailed-card.component.scss
src/Ombi/ClientApp/src/app/components/detailed-card/detailed-card.component.ts
src/Ombi/ClientApp/src/app/discover/components/recently-requested-list/recently-requested-list.component.html
src/Ombi/ClientApp/src/app/discover/components/recently-requested-list/recently-requested-list.component.ts
src/Ombi/wwwroot/translations/en.json

Before:
After:
Tooltips help understand what each button does:

Add deny option to recently requested section

---

src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.html
src/Ombi/ClientApp/src/app/discover/components/genre/genre-button-select.component.html
src/Ombi/ClientApp/src/app/discover/components/genre/genre-button-select.component.scss
src/Ombi/ClientApp/src/app/discover/components/genre/genre-button-select.component.ts
src/Ombi/ClientApp/src/app/discover/components/index.ts

From discovery page can now view a list of buttons that represent each genre.  When user clicks on a genre button they will be taken to a page of movies within that genre.

Search by genre

---

src/Ombi.Core/Senders/MusicSender.cs

Discussed and tested manually in https://github.com/Lidarr/Lidarr/issues/3597#issuecomment-1530804055
Fixes #3597

Change montior to Existing to properly add artist

---

src/Ombi/ClientApp/src/app/requests-list/components/albums-grid/albums-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.html
src/Ombi/ClientApp/src/app/settings/failedrequests/failedrequests.component.html
src/Ombi/ClientApp/src/app/settings/failedrequests/failedrequests.component.ts
src/Ombi/ClientApp/src/app/settings/issues/issues.component.html
src/Ombi/ClientApp/src/app/settings/jobs/jobs.component.html
src/Ombi/ClientApp/src/app/settings/massemail/massemail.component.html
src/Ombi/ClientApp/src/app/settings/notifications/gotify.component.html
src/Ombi/ClientApp/src/app/settings/notifications/mattermost.component.html
src/Ombi/ClientApp/src/app/settings/notifications/mobile.component.html
src/Ombi/ClientApp/src/app/settings/notifications/newsletter.component.html
src/Ombi/ClientApp/src/app/settings/notifications/pushbullet.component.html
src/Ombi/ClientApp/src/app/settings/notifications/pushover.component.html
src/Ombi/ClientApp/src/app/settings/notifications/slack.component.html
src/Ombi/ClientApp/src/app/settings/notifications/telegram.component.html
src/Ombi/ClientApp/src/app/settings/notifications/webhook.component.html
src/Ombi/ClientApp/src/app/settings/usermanagement/usermanagement.component.html
src/Ombi/ClientApp/src/app/usermanagement/usermanagement-user.component.html

Fixes #4908 
Fixes #4836
This migrates elements that were still using Bootstrap to Material: buttons, inputs, checkboxes, table.

Fix various styling issues

---

src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.html
src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.ts

Hi I fixed an error about the `normalForm` in the Radarr Settings, this is my first contribution here, I hope this PR meet the standards :slightly_smiling_face:.
This error happens because the `normalForm` component is nested within an `ngIf`, waiting for the `form` variable to be initialized.
In the `ngOnInit` method, when the `radarrFacade.state$()` emits a value, we synchronously initialize the form and try to access the `changes` field of the `normalForm` reference one after the other, but the `normalForm` remains `undefined` since the template has not yet been updated.
Fixes Ombi-app/Ombi#4994

fix(radarr-settings): this.normalForm is undefined

---

.github/workflows/automation-tests.yml
.github/workflows/build.yml
.github/workflows/chromatic.yml
.github/workflows/pr.yml
src/Ombi.Api.Plex/Models/Friends/PlexFriends.cs
src/Ombi.Schedule.Tests/PlexUserImporterTests.cs
src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs

fix(user-import): Do not import users that do not have access to the server
