PlexRequests.Core/SettingModels/PlexRequestSettings.cs
PlexRequests.Core/Setup.cs
PlexRequests.UI/Modules/SearchModule.cs
PlexRequests.UI/Program.cs
PlexRequests.UI/Views/Admin/Settings.cshtml

separate checkboxes in the settings screen separating out the approval
by tv or movie.

approve tv shows or movies

---

PlexRequests.UI/Modules/SearchModule.cs
PlexRequests.UI/Views/Requests/Index.cshtml
PlexRequests.UI/Views/Search/Index.cshtml

Use HTTPS for poster images, this removes the mixed-content warnings when serving the application via an HTTPS reverse proxy

Use HTTPS for the poster images

---

PlexRequests.UI/Views/Shared/Partial/_Head.cshtml

This fixes issue #537 where the navigation wouldn't have the correct encoding hence not displaying åäö and other characters correctly.
Solved by setting encoding to be utf-8.

Set meta charset to be utf-8

---

PlexRequests.Core/SettingModels/PlexRequestSettings.cs
PlexRequests.UI/Modules/DonationLinkModule.cs
PlexRequests.UI/PlexRequests.UI.csproj
PlexRequests.UI/Resources/UI.resx
PlexRequests.UI/Resources/UI1.Designer.cs
PlexRequests.UI/Views/Admin/Settings.cshtml
PlexRequests.UI/Views/Shared/Partial/_Navbar.cshtml

I added the options for custom donate button, but the actual implementation of the button its self Im a little unsure on. 
Id like to add a configurable button that shows up next to the existing donate, and have 2
"Donate to PlexRequests" "Donate to *Library Maintainer"
I can see where the existing one is setup in _Navbar, however since thats a partial thats rendered from the layout, Im not sure how to go about getting the data from settings. everything in navbar comes from Context. I think passing a model into layout would be the wrong choice, another option is just an endpoint somewhere that can get fetched and setup with an ajax call. But that also feels too complicated for a simple task. 
All I want/need to do is check the values of the settings, and render a new button if they exist.

Added Paypalme options, no UI yet

---

PlexRequests.UI/Helpers/BaseUrlHelper.cs

When the base url is set, resource file imports need a forward slash at
the beginning. Since it's missing from the datepicker.min.css link,
the Landing Page fails to load correctly causing odd behavior.

Fix boostrapper-datetimepicker imports (#586)

---

Ombi.UI/Views/Issues/Details.cshtml

Just a small change to put a space between the colon and the admin message to fix:
Untested but such a small change I cannot see it breaking anything.

Fix small typo in ticket overview page

---

Ombi.Services/Jobs/RecentlyAdded.cs
Ombi.Services/Jobs/Templates/RecentlyAddedTemplate.html

Fixed newsletter rendering `<hr>` outside of html spec causing WebKit based email rendering to show a lot of hr tags at the top of the email.

Fix Newsletter HTML issues

---

Ombi.Core/SettingModels/UserManagementSettings.cs
Ombi.Helpers/Permissions/Permissions.cs
Ombi.UI/Modules/RequestsModule.cs
Ombi.UI/Views/UserManagementSettings/UserManagementSettings.cshtml

I've created a user permission that allows non-admins to see who made the requests.
If the site is configured to allow login without a password, this will expose how to log in as other users, but I don't think that should be a consideration.

Added permission to see who made requests.

---

Ombi.Helpers/PlexHelper.cs

Fixing the broken link to app.plex.tv for the "view in plex" button
Fix for: #1236

Fixing #1236  the broken  link "view in plex" button.

---

Ombi.UI/Views/Search/Index.cshtml

iOS doesn't support input autofocusing (or the jQuery `focus()` event) so when you open the search screen, there's no indicator for what happens next.
I tried clicking the magnifying glass to bring up a search box - this adds placeholders so the user knows where to tap.
Before:
<a href="https://user-images.githubusercontent.com/430255/27756842-d6855f24-5dc0-11e7-8dff-9836c9718cde.jpg" target="_blank"><img src="https://user-images.githubusercontent.com/430255/27756842-d6855f24-5dc0-11e7-8dff-9836c9718cde.jpg" alt="img_2915" width="320" style="max-width:100%;"></a>
After:
<a href="https://user-images.githubusercontent.com/430255/27756844-dee07794-5dc0-11e7-85d9-40db1cedcfa3.jpg" target="_blank"><img src="https://user-images.githubusercontent.com/430255/27756844-dee07794-5dc0-11e7-85d9-40db1c …

Add placeholders to search inputs

---

src/Ombi.Notifications/GenericEmailProvider.cs
src/Ombi.Settings/Settings/Models/Notifications/EmailNotificationSettings.cs
src/Ombi/ClientApp/app/interfaces/INotificationSettings.ts
src/Ombi/ClientApp/app/settings/notifications/emailnotification.component.html
src/Ombi/ClientApp/app/settings/notifications/emailnotification.component.ts

It allows for the disabling of TLS/SSL as well as the ability to disable certificate validation when sending notification emails.

This adds two fields to the Email Notifications settings page. 

---

README.md

Former gif exceed the limit on external ressourceses in the github readme - I did not know that. Hehe, my bad!
The gif has been resized and optimized.

Fix "content length error" on preview gif

---

src/Ombi/ClientApp/app/app.component.html

Issues link currently has the same element ID as the Requests link. This makes styling hard, and it doesn't seem intended anyway.

 Fix duplicated "Requests" element ID on new Issues link

---

src/Ombi.Api.Slack/SlackApi.cs

Adding link_names parameter to ensure that incoming webhooks get properly parsed for user mentions. Without this user mentions remain as plain text.

Fix user mentions in Slack notifications

---

src/Ombi.Api.Emby/EmbyApi.cs

I am unable to access Ombi with my emby connect account. I've got a 401.
I had the same problem with a Kodi addon. It is stated in the [emby authentication docs](https://github.com/MediaBrowser/Emby/wiki/Authentication#authenticating-a-user) that we are supposed to provide 3 fields for the password: *plain*, *md5*, and *sha1*.
Actually it seems that the only required field in the future will be the plain password one.
I have no idea why they would need the plain password, it's pretty bad pratice to send it in clear even over HTTPS but otherwise I can't login.
My emby account is pretty old, maybe that's why it's stored plain ?
Anyway I added the missing *pw* field to the login request. It should work just fine now.
PS: We should at least check if https is enabled before using this field …

Add plain password for emby login

---

src/Ombi/ClientApp/app/landingpage/landingpage.component.scss

Although we should probably tint the entire background on mobile. Looks a bit weird now with long texts.

 Fix #1599

---

src/Ombi.Api/Api.cs
src/Ombi.Api/HttpRequestExtnesions.cs
src/Ombi.Api/Ombi.Api.csproj
src/Ombi.Api/Request.cs
src/Ombi.DependencyInjection/IocExtensions.cs
src/Ombi.Schedule/JobSetup.cs
src/Ombi.Schedule/Jobs/Ombi/IRefreshMetadata.cs
src/Ombi.Schedule/Jobs/Ombi/RefreshMetadata.cs
src/Ombi.Schedule/Ombi.Schedule.csproj
src/Ombi.Settings/Settings/Models/JobSettings.cs
src/Ombi.Settings/Settings/Models/JobSettingsHelper.cs
src/Ombi.Store/Repository/IPlexContentRepository.cs
src/Ombi.Store/Repository/IRepository.cs
src/Ombi.Store/Repository/PlexContentRepository.cs
src/Ombi.Store/Repository/Repository.cs
src/Ombi.TheMovieDbApi/IMovieDbApi.cs
src/Ombi.TheMovieDbApi/Models/FindResult.cs
src/Ombi.TheMovieDbApi/Models/TvExternals.cs
src/Ombi.TheMovieDbApi/TheMovieDbApi.cs
src/Ombi/ClientApp/app/interfaces/ISettings.ts
src/Ombi/ClientApp/app/services/settings.service.ts
src/Ombi/ClientApp/app/settings/jobs/jobs.component.html
src/Ombi/ClientApp/app/settings/jobs/jobs.component.ts
src/Ombi/ClientApp/app/settings/settings.module.ts
src/Ombi/Controllers/SettingsController.cs
src/Ombi/Models/CronTestModel.cs
src/Ombi/Models/CronViewModelBody.cs
src/Ombi/Models/JobSettingsViewModel.cs
src/Ombi/Ombi.csproj
src/Ombi/package-lock.json

We now can refresh the Plex Metadata in our database. For example if the Plex Agent for TV Shows is TheMovieDb, we will use that and populate the IMDB Id and TheTvDb Id's so we can accuratly match and search things.
Also improved the Job settings page so we can Test CRON's and we also validate them.

Added the ability to refresh out backend metadata

---

src/Ombi.Core/Engine/TvRequestEngine.cs

This small change makes the TV request list sorting a bit more intuitive by ordering by the request date in descending order. This makes approving newly requested shows much easier.

Sort TvRequests by latest request

---

src/Ombi/ClientApp/app/search/seriesinformation.component.ts

Currently it's not possible to edit an already requested series, because the request params are populated with already requested episodes in addition to the selected ones. I hope this will fix it.

Use selected episodes in submitRequest

---

src/Ombi/ClientApp/app/requests/tvrequest-children.component.html

Pretty sure that Firefox's behavior is incorrect in this case. Since the floated content is the full width of the container, it *should* push the rest of the content down, like it does in chrome. ¯\_(ツ)_/¯

Add clearfix class. Closes #2486

---

src/Ombi.Core/Engine/MovieRequestEngine.cs
src/Ombi.Core/Engine/TvRequestEngine.cs
src/Ombi.Schedule.Tests/NewsletterTests.cs

Fixes bug which would cause the countdown to the next request to be wrong/absent.
The json being returned from the `GetRemainingRequests` action in `MovieRequestEngine`/`TvRequestEngine` didn't contain a timezone, so relied on the client to provide the timezone, causing the bug.
Also adds a bodge fix to the `NewsletterTests.cs` test. Although the test still fails, the build fails without this change, due to the wrong number of params passed to `NewsletterJob`.
**Before change**
Note that the user has no items left in their quota, however the countdown for the next item is not shown:
**After change**
Count down timer displays correctly:

Fix timezone bug

---

src/Ombi.Core/Engine/Interfaces/IRequestEngine.cs
src/Ombi.Core/Engine/MovieRequestEngine.cs
src/Ombi.Core/Engine/TvRequestEngine.cs
src/Ombi.Core/Models/UI/UserViewModel.cs
src/Ombi/ClientApp/app/interfaces/IUser.ts
src/Ombi/ClientApp/app/usermanagement/usermanagement-add.component.ts
src/Ombi/ClientApp/app/usermanagement/usermanagement.component.html
src/Ombi/ClientApp/app/usermanagement/usermanagement.module.ts
src/Ombi/Controllers/IdentityController.cs
src/Ombi/wwwroot/translations/en.json

Adds information about each users remaining tv/movie quota to the user management page.
Also fixes a bug which would prevent TV requests from being logged if the user requesting has auto approve enabled. This would effectively allow those users to request an infinite number of TV shows.

Display quota on user managment page

---

src/Ombi.Api.Lidarr/Models/CommandResult.cs

This removes the Sonarr legacy command result variables and changes them to their newer values. These  legacy mappings have been removed in Lidarr (and Sonarr V3 api). 
I know you guys are not using for anything yet, but just wanted to make sure there were not issues down the line.

Fixed: Removes Lidarr legacy command result variables

---

src/Ombi/ClientApp/app/requests/movierequests.component.html

After fixing #2564 I have noticed that Radarr has the same options available. Applying the same fix for consistency.

Bug/2564 hide Radarr options when only 1 option available

---

src/Ombi/ClientApp/app/app.component.html
src/Ombi/wwwroot/translations/da.json
src/Ombi/wwwroot/translations/de.json
src/Ombi/wwwroot/translations/en.json
src/Ombi/wwwroot/translations/es.json
src/Ombi/wwwroot/translations/fr.json
src/Ombi/wwwroot/translations/it.json
src/Ombi/wwwroot/translations/nl.json
src/Ombi/wwwroot/translations/no.json
src/Ombi/wwwroot/translations/pl.json
src/Ombi/wwwroot/translations/pt.json
src/Ombi/wwwroot/translations/sv.json

This PR is for issue #2407. It restricts language selector to always show native language name. 
I took all native language names from the respective translation files except for Swedish one. I believe that it should Svenska instead. Let me know if you would like this change done differently.

Changes language selector to always show native language name.

---

src/Ombi/ClientApp/app/settings/massemail/massemail.component.html
src/Ombi/ClientApp/app/settings/massemail/massemail.component.ts

A fix for issues #2298. 
I have noticed that on Safari 'click' trigger was calling to selectSingleUser function after ngModel does the binding, therefore unticking the just ticked checkbox. Since that function was doing nothing other than flipping a boolean value I removed it and left this functionality up to ngModel to handle. 
P.S. Another fix that could have worked in this case is changing 'click' trigger to 'ngModelChange' one. This one seems to be consistent across the browsers.

Fixes untickable mass email checkboxes in Safari.

---

src/Ombi/Controllers/IdentityController.cs

Fix for #2658. Looks like user's alias property hasn't been mapped at controller level.

Maps alias email variable for welcome emails.

---

build.cake

Since the last time the CI passed, 2 versions have been released: [Cake.Incubator releases](https://github.com/cake-contrib/Cake.Incubator/releases)
Downgrading Cake.Incubator fixes the build.

Fix cake build by setting Incubator version

---

README.md
src/Ombi.Api.Gotify/GotifyApi.cs
src/Ombi.Api.Gotify/IGotifyApi.cs
src/Ombi.Api.Gotify/Ombi.Api.Gotify.csproj
src/Ombi.Core/Models/UI/GotifyNotificationViewModel.cs
src/Ombi.DependencyInjection/IocExtensions.cs
src/Ombi.Helpers/LoggingEvents.cs
src/Ombi.Helpers/NotificationAgent.cs
src/Ombi.Mapping/Profiles/SettingsProfile.cs
src/Ombi.Notifications/Agents/GotifyNotification.cs
src/Ombi.Notifications/Agents/Interfaces/IGotifyNotification.cs
src/Ombi.Notifications/Ombi.Notifications.csproj
src/Ombi.Settings/Settings/Models/Notifications/GotifySettings.cs
src/Ombi.sln
src/Ombi/ClientApp/app/interfaces/INotificationSettings.ts
src/Ombi/ClientApp/app/services/applications/tester.service.ts
src/Ombi/ClientApp/app/services/settings.service.ts
src/Ombi/ClientApp/app/settings/notifications/gotify.component.html
src/Ombi/ClientApp/app/settings/notifications/gotify.component.ts
src/Ombi/ClientApp/app/settings/settings.module.ts
src/Ombi/ClientApp/app/settings/settingsmenu.component.html
src/Ombi/Controllers/External/TesterController.cs
src/Ombi/Controllers/SettingsController.cs

[Gotify](https://gotify.net/) is a self-hosted notification service. This PR adds Gotify as another provider for notifications.
* `ApplicationToken` is generated from Gotify and is used to identify the app (here Ombi).
* `Priority` defines the priority of the notification.
This has been tested on my instance of Ombi.

Add Gotify as notification provider

---

CHANGELOG.md
src/Ombi.Helpers/EmbyHelper.cs
src/Ombi/ClientApp/app/settings/emby/emby.component.html

Update EmbyURL. Fixes #3078
Emby changed the URL starting with the Emby version v4.2.0
Note: This will probably break support for Jellyfin.

Update EmbyURL. Fixes #3078

---

.github/.github/workflows/test.workflow
.github/workflows/aspnetcore.yml
.github/workflows/test.workflow
src/Ombi.Core/Engine/MusicSearchEngine.cs
src/Ombi.Helpers.Tests/StringHelperTests.cs
src/Ombi.Helpers/StringHelper.cs
src/Ombi.Mapping/Profiles/TvProfile.cs
src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs

The new string extension method ToHttpsUrl ensures that URLs starting with "https" are no longer turned into "httpss"
The commit also replaces all occurances of the error prone .Replace("http", "https") in the whole solution.

Fixes issue #3195

---

src/Ombi.Notifications/Agents/SlackNotification.cs

It looks like the Slack notification agent was using the wrong notification type in the request declined method.

Fixes issue #3153

---

CHANGELOG.md
src/Ombi/ClientApp/app/search/moviesearch.component.html
src/Ombi/ClientApp/app/search/search.component.scss
src/Ombi/ClientApp/app/search/tvsearch.component.html
src/Ombi/ClientApp/styles/base.scss

Fixes the "Suggestions" and "Refine" buttons overlapping the search bar on mobile devices (specifically phones) in portrait mode. The alternative view is only present when the width is 450px or less.
Before            |  After
:-------------------------:|:-------------------------:
Ignore the "TV Shows" tab missing from the "Before" as I have it hidden on my prod server. Also ignore the icons missing from the "After" as I'm not sure why they don't show up in my local environment (any pointers on fixing this?).

Fix search bar overlap on mobile

---

src/Ombi.Core/Engine/Demo/DemoTvSearchEngine.cs
src/Ombi.Core/Engine/TvSearchEngine.cs
src/Ombi.Core/Models/Search/SearchViewModel.cs
src/Ombi.Core/Rule/Rules/Search/ExistingRule.cs
src/Ombi.Notifications/NotificationMessageCurlys.cs

Just adding the `RequestId` property into the notification's data. I believe this would essentially help for the Webhook kind. For instance, in my case, this will allow me to easily keep track of a request from a Telegram bot.

Add RequestId variable in notification's data

---

src/Ombi.Store/Context/OmbiContext.cs

Due to changes in Client vs. Server Evaluation in EF, this statement could not be evaluated on the server-side

Fixes #3399

---

src/Ombi/ClientApp/app/search/tvsearch.component.html

Links for TV shows were just relative paths to their imdb ID. 
ex: `href="tt0944947"` for Game of Thrones

Fix IMDB links for TV shows not working

---

src/Ombi.Store/Context/OmbiContext.cs

Before: Hello! Your request for The Warriors on Plex Server! This is now
available! :)
After: Hello! Your request for The Warriors on Plex Server is now
available! :)
I feel this flows better and the sentence sounds more complete.
Thank you for this project, I use it almost daily 😄

Improve wording for Now Available notification template

---

src/Ombi/Views/Shared/_Layout.cshtml

With the smartquotes, only the first word of the custom app gets loaded in inside apps that use those tags for previews.
For example, my Ombi instance has the name set as "Bloom Plex Requests" but when sent via iMessage, the preview only shows "Bloom as the title.

Replace smartquotes in meta info

---

src/Ombi/ClientApp/src/styles/material-overrides.scss

this makes the text entry boxes in the settings pages fill their element instead of being so narrow.
vs OLD
IM LEARNING!

settings textbox width fix

---

src/Ombi.Store/Context/Sqlite/ExternalSqliteContext.cs
src/Ombi.Store/Context/Sqlite/OmbiSqliteContext.cs
src/Ombi.Store/Context/Sqlite/SettingsSqliteContext.cs
src/Ombi/Program.cs

This pull requests fixes:
* Console output for url+port in use.
* SQLite unique constrain exception.
> Note: ExecuteSqlCommand is now marked as obsolete so I changed it to ExecuteSqlRaw.

Cleanup console output during startup.

---

src/Ombi/Controllers/V1/TokenController.cs

Added logging of failed login for Fail2Ban, supports reverse proxy and direct connection, tested directly and using NGINX.
Fail2Ban jail for testing:
[INCLUDES]
before = common.conf
[Definition]
failregex = ^.*Failed login attempt by IP: <ADDR>.*$
ignoreregex =

Added logging of failed login for Fail2Ban

---

src/Ombi/ClientApp/src/styles/shared.scss

At the moment, as of 9e0986ce9fcb62df20fe22c7c6dcee70445d7694. the `overflow` css property is set to `auto`. This causes a windowing effect on MobileKit devices (iOS, iPadOS).
After setting the `overflow` property to `initial`(Which is the default, this will actually set to: `visible`) the following outcome is observed:
I have tested this property on all the devices as I have on hand:
- Safari (MacOS)
- Chromium (MacOS)
- Firefox (MacOS)
And it doesn't break anything as far as I can see. Happy to open a discussion if this implementation is non-standard

Fix WebKit windowing effect

---

src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.html
src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.scss

basically got rid of some extra padding to the layout change buttons. and hid them on mobile since they it doesn't really need to be there on mobile.
let me know.

what do you think?

---

src/Ombi.Api.Trakt/TraktApi.cs

Fixes one of the issues mentioned in #3717.

Ignores Trakt exceptions when retrieving optional tv show information.

---

src/Ombi.Api.Radarr/Models/RadarrAddMovie.cs

In both the v2 and v3 Radarr API responses, the images property of a movie is a list of Image objects. This has never been a list of strings and causes errors with Ombi V3 and Radarr V3 given V3 returns all metadata on add, V2 always returned an empty list on a movie add (of the same image object as V3). 
It seems this has been an issue since the beginning in Ombi, but wasn't noticed with V2. 
Option 2 just remove it given its not used anyway, we are getting user complaints for those that don't want to use v4 due to bugs... can we please backport this and release, its a couple lines.

Fixed: Don't Type RadarrAddMovieResponse Image list to String

---

src/Ombi.Api.Radarr/Models/V2/SystemStatus.cs
src/Ombi.Core/Models/TesterResultModel.cs
src/Ombi/ClientApp/src/app/interfaces/ITester.ts
src/Ombi/ClientApp/src/app/interfaces/index.ts
src/Ombi/ClientApp/src/app/services/applications/tester.service.ts
src/Ombi/ClientApp/src/app/settings/lidarr/lidarr.component.ts
src/Ombi/ClientApp/src/app/settings/radarr/radarr.component.ts
src/Ombi/ClientApp/src/app/settings/sonarr/sonarr.component.ts
src/Ombi/Controllers/V1/External/TesterController.cs

If the API returns a base URL that differs from the one currently set, output that in the error message.
Currently we show that the test passed, which is definitely wrong, as even though Sonarr/Radarr return a result here, they will fail for POST requests if the base URL is not set correctly, which is pretty confusing.

Provide the base URL if possible for Sonarr/Radarr

---

src/Ombi/ClientApp/src/app/services/requestretry.service.ts

Fixes #3870
The base URL ends with a slash, so adding another one here results in two, which leads to an HTTP 500.

Fix double-slash in failed requests removal URL

---

src/Ombi.Core/Senders/TvSender.cs

Ombi implicitly trusts that the quality/rootfolder override is set correctly, and causes issues downstream.
Line `258` in [TvSender.cs](https://github.com/Ombi-app/Ombi/tree/develop/src/Ombi.Core/Senders/TvSender.cs#L258) it tries to add a series, but the `AddSeries` function in [SonarrApi.cs](https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.Api.Sonarr/SonarrApi.cs#L92) fails to validate the `NewSeries` object since the `qualityProfileId` attribute is set to `0`. In the end it assumes the series is added in Sonarr and causes a API request with series id set to `0` which causes the following error.
```
[Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://SONARR_HOST/sonarr/api/series/0
```
#3194 could be related to this.

Verify Sonarr quality/rootfolder override

---

src/Ombi.Core/Senders/TvSender.cs

I realized that in #4116 I overlooked that it always sets the `RootFolder` in line `171` and `191` so the rootfolder check further down does nothing.

fixes rootfolder selection in sonarr

---

src/Ombi.TheMovieDbApi/Models/FullMovieInfo.cs

Anime shows where being wrongly classified as "Standard" by Sonarr and it seems themoviedb API json response is not handled correctly.
The below snippet is from the following API call: `curl 'https://api.themoviedb.org/3/tv/13916?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=keywords' | python3 -m json.tool`
```
"type": "Scripted",
"vote_average": 8.7,
"vote_count": 2030,
"keywords": {
"results": [
{
"name": "police",
"id": 6149
},
{
```

themoviedb keywords attribute api change

---

src/Ombi.TheMovieDbApi/Models/FullMovieInfo.cs

I was a bit quick when making #4128 to realize that the movie api returned a different attribute for the keywords.
`curl 'https://api.themoviedb.org/3/movie/137113?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=keywords' | python3 -m json.tool` returned the following.
```
"title": "Edge of Tomorrow",
"video": false,
"vote_average": 7.6,
"vote_count": 10445,
"keywords": {
"keywords": [
{
"id": 563,
"name": "deja vu"
},
{
"id": 1521,
"name": "time warp"
},
```

fixes movie keywords

---

src/Ombi/ClientApp/src/app/user-preferences/components/user-preference/user-preference.component.html
src/Ombi/ClientApp/src/app/user-preferences/components/user-preference/user-preference.component.scss

Fixes username overflowing onto profile picture in certain mobile resolutions. 
Makes spacing on the page a bit more consistent.
Before: 
After:

User preferences page style improvements.

---

src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.html
src/Ombi/ClientApp/src/app/media-details/media-details.component.scss

Quick commit to fix the social icon container not showing on the TV details page

Fix for overlay of the social icons container

---

src/Ombi/ClientApp/src/app/media-details/components/movie/panels/movie-information-panel.component.html

Previous value `{{baseUrl}}images/tmdb-logo.svg` leads to broken image requests, e.g. `server.com/ombiimage/tmdb-logo.svg`. We need to trail the `baseURL` with a `/` to ensure the correct path, e.g. `server.com/ombi/image/tmdb-logo.svg`. See also lines 9 and lines 14.

Fix TMDB logo URL

---

src/Ombi/ClientApp/src/app/my-nav/nav-search.component.html

So on page load a user can immediately start typing a search without having to manually navigate to it. Also a big bonus for accessibility

Autofocus the Search field

---

src/Ombi.Settings/Settings/Models/External/TheMovieDbSettings.cs
src/Ombi.TheMovieDbApi/IMovieDbApi.cs
src/Ombi.TheMovieDbApi/Models/TheMovieDbContainer.cs
src/Ombi.TheMovieDbApi/TheMovieDbApi.cs
src/Ombi/ClientApp/src/app/interfaces/IMovieDb.ts
src/Ombi/ClientApp/src/app/interfaces/ISettings.ts
src/Ombi/ClientApp/src/app/services/applications/themoviedb.service.ts
src/Ombi/ClientApp/src/app/settings/themoviedb/themoviedb.component.html
src/Ombi/ClientApp/src/app/settings/themoviedb/themoviedb.component.ts
src/Ombi/Controllers/V1/External/TheMovieDbController.cs

Hi @tidusjar - opening up this PR now for discussion + feedback.
This is the PR to introduce filtering out genres from the Discover lists.
TheMovieDB API only has the capability to get a list of all genre mappings and unfortunately does not have a lookup api

Filter out Genres from Discover

---

src/Ombi/ClientApp/src/app/issues/issueDetails.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-request-grid/tv-request-grid.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-requests/tv-requests-panel.component.html
src/Ombi/ClientApp/src/app/pipes/UserLocalePipe.ts
src/Ombi/ClientApp/src/app/pipes/pipe.module.ts
src/Ombi/ClientApp/src/app/requests/tvrequest-children.component.html
src/Ombi/ClientApp/src/app/search/moviesearchgrid.component.html
src/Ombi/ClientApp/src/app/search/music/albumsearch.component.html
src/Ombi/ClientApp/src/app/search/seriesinformation.component.html
src/Ombi/ClientApp/src/app/search/tvsearch.component.html
src/Ombi/ClientApp/src/app/shared/chat-box/chat-box.component.html
src/Ombi/ClientApp/src/app/shared/episode-request/episode-request.component.html
src/Ombi/ClientApp/src/app/usermanagement/usermanagement.component.html

Formatting for all short dates is now using window.navigator.language. 
Dates for chat messages are also converted from UTC to local time first.
Let me know if you think using window.navigator.languages[0] (if present) might be a better option in your opinion.

Updates short date formatting to use user's browser preference.

---

src/Ombi.Api/ApiHelper.cs
src/Ombi/ClientApp/src/app/services/searchV2.service.ts
src/Ombi/Controllers/V2/SearchController.cs

Fixes #4065 
There were two issues around the same topic:
- Discover search query from frontend to backend was not properly encoded, so searching for "AC/DC" would break the routing (error 500). I couldn't think of any other routes that may also be affected.
- Query from backend to external APIs were not properly encoded, so searching for "&" would be interpreted as a new query parameter by the external service.
It's a big change but I can't find any regression so far, only better search results.

Better URL encoding

---

src/Ombi.Core/Engine/BaseMediaEngine.cs
src/Ombi.Core/Engine/IMusicRequestEngine.cs
src/Ombi.Core/Engine/Interfaces/IMovieRequestEngine.cs
src/Ombi.Core/Engine/Interfaces/ITvRequestEngine.cs
src/Ombi.Core/Engine/MovieRequestEngine.cs
src/Ombi.Core/Engine/MusicRequestEngine.cs
src/Ombi.Core/Engine/RequestEngineResult.cs
src/Ombi.Core/Engine/TvRequestEngine.cs
src/Ombi/ClientApp/src/app/requests-list/components/albums-grid/albums-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/albums-grid/albums-grid.component.ts
src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.ts
src/Ombi/ClientApp/src/app/requests-list/components/options/request-options.component.ts
src/Ombi/ClientApp/src/app/services/request.service.ts
src/Ombi/Controllers/V1/MusicRequestController.cs
src/Ombi/Controllers/V1/RequestController.cs
src/Ombi/wwwroot/translations/en.json
tests/cypress/tests/requests/requests.spec.ts

Secure role "Manage Own Requests"

---

src/Ombi.Schedule/Jobs/Emby/EmbyContentSync.cs
src/Ombi.Schedule/Jobs/Emby/EmbyEpisodeSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinContentSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinEpisodeSync.cs

There is an offset error in Emby sync: Emby API offset is 0-based and Ombi syncs from 0-99 then from 101-200.
This means the 100th movie, the 100th TV episode of a show, and the 100th show would not get synced. Now if that's not a bug that made me think I was crazy...!

A more reliable Emby and Jellyfin sync

---

src/Ombi/ClientApp/src/app/settings/jobs/jobs.component.html
src/Ombi/ClientApp/src/app/settings/jobs/jobs.component.ts

Add UI for Emby recently added cronjob settings

---

src/Ombi/Extensions/StartupExtensions.cs

the api auth for swagger page has been broken
http://localhost:5000/swagger/index.html
and according to swagger doc
https://swagger.io/docs/specification/authentication/api-keys/
we are setting it up wrong
local test:
able to get response
swagger json config looks good

fix swagger api key auth

---

src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs

Removed some leftover from TVMaze API uses in the newsletter.
Partial fix for #4444
This should hopefully allow for more TV shows to be sent in the newsletter.
Also added some logs to better understand when an item won't be sent to the newsletter, in the hope to come up with a better fix for #4444.

Drop TVMaze from Newsletter

---

src/Ombi.Store/Entities/EmbyEpisode.cs
src/Ombi.Store/Entities/JellyfinEpisode.cs
src/Ombi.Store/Entities/MediaServerContent.cs
src/Ombi.Store/Entities/PlexEpisode.cs

Double episodes have a single Id in the media server. The duplicate check in the newsletter would check against this Id, leading to double episodes being party ignored (only the first episode would be published).

Fix newsletter not publishing double episodes

---

src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs

I find that the newsletter info is cluttered when an old TV show with many seasons is published.
This PR attempts to simplify the episode list:
- Do not list episodes if the series is complete
- Do not list all episodes of a season if the season is complete

Declutter newsletter info for series

---

src/Ombi/ClientApp/src/app/shared/chat-box/chat-box.component.html

Typo from a previous PR broke the "Users" label in the chatbox.

Fix label ID in chatbox page

---

src/Ombi.Notifications.Templates/EmailBasicTemplate.cs
src/Ombi.Notifications.Templates/IEmailBasicTemplate.cs
src/Ombi.Notifications/Agents/EmailNotification.cs
src/Ombi.Notifications/NotificationMessageContent.cs
src/Ombi.Notifications/NotificationMessageCurlys.cs
src/Ombi.Notifications/NotificationMessageResolver.cs

Posters in email notifications are now clickable and redirect to Ombi details page.
Mostly useful IMO to allow for a quick approve/deny action when receiving a notification.

Add a link to Ombi details page in email notifications

---

src/Ombi.Notifications/Agents/EmailNotification.cs
src/Ombi.Notifications/BaseNotification.cs
src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs
src/Ombi.Settings/Settings/Models/Notifications/EmailNotificationSettings.cs
src/Ombi/ClientApp/src/app/interfaces/INotificationSettings.ts
src/Ombi/ClientApp/src/app/settings/notifications/emailnotification.component.html
src/Ombi/ClientApp/src/app/settings/notifications/emailnotification.component.ts
src/Ombi/Controllers/V1/External/TesterController.cs

This removes the generic admin email setting.
Instead we use the email addresses set on the users' profile.
Allows for notifications to many recipients in case of multiple admins.
Email testing now sends the test email to the currently logged in user.

Remove generic admin email in favor of admins' email

---

src/Ombi.Settings/Settings/Models/AuthenticationSettings.cs
src/Ombi/ClientApp/src/app/auth/auth.service.ts
src/Ombi/ClientApp/src/app/interfaces/ISettings.ts
src/Ombi/ClientApp/src/app/login/login.component.ts
src/Ombi/ClientApp/src/app/settings/authentication/authentication.component.html
src/Ombi/ClientApp/src/app/settings/authentication/authentication.component.ts
src/Ombi/Controllers/V1/TokenController.cs

I've a reverse proxy in place, and wanted for some time to integrate user management with SSO.
I've looked at different options and the easiest and possibly most versatile one was to implement header authentication, so that people can authenticate however they see fit on a reverse proxy and just set a header variable to the username to login.
This PR solves this problem by adding a setting in the Authentication page to enable user authentication via header variable, and lets the user specify a variable to use.
If enabled classic authentication is completely bypassed **if the user is found.** 
Needless to say that users have to be created somehow beforehand, either locally, by importing plex/emby.. or possibly in the future via LDAP if the other PR are merged.
If it is enabled, but the …

SSO with Header Authentication

---

src/Ombi/ClientApp/src/app/settings/radarr/components/radarr-form.component.ts

This was lost in the 4K refactoring.

Fix some Radarr settings no longer initialized in settings page

---

src/Ombi.Core/Engine/V2/IMultiSearchEngine.cs
src/Ombi.Core/Engine/V2/MultiSearchEngine.cs
src/Ombi.TheMovieDbApi/IMovieDbApi.cs
src/Ombi.TheMovieDbApi/TheMovieDbApi.cs
src/Ombi/ClientApp/src/app/services/applications/themoviedb.service.ts
src/Ombi/ClientApp/src/app/services/searchV2.service.ts
src/Ombi/ClientApp/src/app/settings/themoviedb/themoviedb.component.ts
src/Ombi/ClientApp/src/app/shared/components/genre-select/genre-select.component.ts
src/Ombi/Controllers/V1/External/TheMovieDbController.cs
src/Ombi/Controllers/V2/SearchController.cs

Allows for localized genres selection in the advanced search popup, and as a side effect in /Settings/TheMovieDb.

Localize genres filter

---

src/Ombi/Ombi.csproj
src/Ombi/Startup.cs
src/Ombi/appsettings.Development.json
src/Ombi/appsettings.json

This will prevent production setups from being flooded with debug logs whilst still allowing debug logs for developers.
See https://github.com/serilog/serilog-settings-configuration

Make Serilog configurable and default minimum level to Information

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.html
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.scss
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts

Before this change, it would show as "Approved" if the TV show was listed in Sonarr, or without a status if Sonarr was not setup.

Display 'partly available' status on TV show discover card

---

src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs
src/Ombi.Core/Models/Search/SearchTvShowViewModel.cs
src/Ombi.Core/Models/Search/V2/SearchFullInfoTvShowViewModel.cs
src/Ombi.Core/Rule/Rules/Search/ExistingRule.cs
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts
src/Ombi/ClientApp/src/app/interfaces/ISearchTvResultV2.ts
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.html

TV shows having all episodes denied will show as "Denied" on the discover page (pending https://github.com/Ombi-app/Ombi/pull/4579) and on the details page.
Before:
After:
Partially denied TV shows behave the same as before:

Enhance display of denied TV shows

---

src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs
src/Ombi.Core/Models/Search/SearchTvShowViewModel.cs
src/Ombi.Core/Models/Search/V2/SearchFullInfoTvShowViewModel.cs
src/Ombi.Core/Rule/Rules/Search/ExistingRule.cs
src/Ombi.Store/Entities/Requests/SeasonRequests.cs
src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts
src/Ombi/ClientApp/src/app/interfaces/ISearchTvResultV2.ts
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.html

- Fixes an issue where individual episodes would all show as denied if an other episode of that show was denied. 
- (API only) A TV show will be 'Denied' if all its episodes are denied (replaces the very recently added 'FullyDenied' property).
- (API only) The denied reason is now exposed for individual episodes.

Better 'denied' request status for TV shows

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.scss
src/Ombi/ClientApp/src/app/media-details/components/tv/panels/tv-request-grid/tv-request-grid.component.scss

Better color codes for request statuses

---

src/Ombi.Schedule/Jobs/Emby/EmbyAvaliabilityChecker.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinAvaliabilityChecker.cs

Fix requests when 4k content is available and 4k feature is disabled

---

src/Ombi.Core/Senders/TvSender.cs

Follow-up of https://github.com/Ombi-app/Ombi/pull/4589
Fixes https://github.com/Ombi-app/Ombi/issues/4588
Since seasonpass endpoint isn't reliable for us, I suggest to re-use the individual episode logic when the full season is requested and use the series endpoint. 
In that case we will unmonitor every episode of the season, then monitor them again. I agree it's not ideal. Maybe we could optimize this but I was not sure why a similar logic about previously monitored episodes had been commented out.

Sonarr sync: stop using seasonpass API

---

src/Ombi.Store/Context/OmbiContext.cs

If the Title of the show is not menitoned it can be unclear what episodes are now available.

Add Title to Partially Available Message

---

src/Ombi/ClientApp/src/app/issues/issuestable.component.html
src/Ombi/ClientApp/src/app/requests-list/components/albums-grid/albums-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.html
src/Ombi/ClientApp/src/app/usermanagement/usermanagement.component.html
src/Ombi/ClientApp/src/styles/Styles.scss

I assume it's best for accessibility, but also this allows for middle-clicking to open the page in a new tab.

Transform buttons with link into anchors

---

src/Ombi.Core/Engine/MovieRequestEngine.cs
src/Ombi.Core/Engine/MusicRequestEngine.cs
src/Ombi.Core/Engine/TvRequestEngine.cs

The subscribe button currently still shows when the request is available or denied. 
This PR will hide the button when the request has reached the end of its livecycle.
I anticipated the fix on TV and albums even though I couldn't find that option available in the web app. I'm assuming it wasn't ported to the new V4 layout?

Hide subscribe button when request is closed

---

src/Ombi.Schedule/Jobs/Emby/EmbyContentSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinContentSync.cs
src/Ombi.Store/Repository/EmbyContentRepository.cs
src/Ombi.Store/Repository/IMediaServerContentRepository.cs
src/Ombi.Store/Repository/JellyfinContentRepository.cs
src/Ombi.Store/Repository/MediaServerRepository.cs
src/Ombi.Store/Repository/PlexContentRepository.cs

This addresses the issue mentioned here: https://github.com/Ombi-app/Ombi/issues/4472#issuecomment-1030160547
This should prevent the need of clearing data if a media was manually reidentified due to automatic detection failing.
At first glance it seems Plex sync doesn't do it but the sync has a completely different logic so probably the issue doesn't occur there.

Detect reidentified content in Emby and Jellyfin

---

src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs

Fixes https://github.com/Ombi-app/Ombi/issues/4444
Technically it doesn't actually fix it, but when I came back to analyzing this issue, I found out it's now almost impossible for it to occur. The only case would be if there's an issue on TMDB side or if a series doesn't have a TMDB ID (not sure this is possible at all since we check the IDs upon media sync).
I just added a double check on the TMDB ID for series. It was already there for movies.

Newsletter: better log if an item is not published

---

src/Ombi.Core/Engine/MovieSearchEngine.cs
src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs
src/Ombi.TheMovieDbApi/IMovieDbApi.cs
src/Ombi.TheMovieDbApi/TheMovieDbApi.cs

Before:
After:
Upcoming TV would use filter release_date which does not exist for TVs so this basically turned out to be exactly the same as the popular section. I'm surprised this went unnoticed for so long (by myself included!).
We now use the first air date. I fiddled around and found the sweet spot to be shows that will release in the next month, as opposed to upcoming movies which looks for movies released between D+7 and D+27. 
Now that's a quick win 😃

feat(discover): Show more relevant shows in upcoming TV

---

src/Ombi.Api.Emby/EmbyApi.cs
src/Ombi.Api.Jellyfin/JellyfinApi.cs
src/Ombi.Schedule/Jobs/Emby/EmbyEpisodeSync.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinEpisodeSync.cs

- Use a more reliable filter to missing items. IsVirtualItem is not an available filter ; instead isMissing has found itself to be reliable.
- Allow syncing files containing more than 2 episodes.

Minor changes to Emby and Jellyfin sync

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.html

Added a simple addition to the "top-left" element's id in the form of the media type, this enables theming individual media types which isn't possible in the current setup, added to id so it won't break other hard-coded CSS/existing themes.

Added media type tag to media type text

---

src/Ombi.Api.SickRage/Models/SickRageEpisodeStatus.cs

episode results returned from SiCKRAGE API when changing status of episodes is an array of objects, this merge request corrects SickRageEpisodeSetStatus model data property to accommodate that

Fixes SickRageEpisodeSetStatus model to accept array of objects via data prop

---

src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/movie/movie-details.component.ts
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.html
src/Ombi/ClientApp/src/app/media-details/components/tv/tv-details.component.ts

added checks and string formatting in the case of having a missing poster on tmdb to both tv and movies, removed the hard coded tmdb url from the html template and moved into component.

Missing Poster broken link fix

---

src/Ombi.Helpers.Tests/PagnationHelperTests.cs
src/Ombi.Helpers/PaginationHelper.cs

/api/v2/Search/movie/popular/40/40 returns only 20 results when it should return 40 of them.
This seems to happen only if the starting point is a factor of 20 and greater than 20.

fix(API): Fix pagination in some edge cases

---

src/Ombi.Core/Engine/MovieSearchEngine.cs
src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs
src/Ombi.Core/Models/Search/SearchViewModel.cs

Follow up of https://github.com/Ombi-app/Ombi/pull/4585
API consumers of Subscribed and ShowSubscribe fields should migrate from /search/movie/* endpoint to /Request/movie/info/*.
For the record, these fields could not be trusted because they were cached on a global level whereas these fields are user-dependent. The Request endpoint is not cached and those fields have been fixed for movies in https://github.com/Ombi-app/Ombi/pull/4585.

perf: stop populating obsolete subscribe fields from search endpoint

---

src/Ombi/ClientApp/src/app/app.module.ts
src/Ombi/ClientApp/src/app/components/image-background/image-background.component.html
src/Ombi/ClientApp/src/app/components/image-background/image-background.component.scss
src/Ombi/ClientApp/src/app/components/image-background/image-background.component.ts
src/Ombi/ClientApp/src/app/components/index.ts
src/Ombi/ClientApp/src/app/components/modules.ts
src/Ombi/ClientApp/src/app/interfaces/IImages.ts
src/Ombi/ClientApp/src/app/landingpage/landingpage.component.html
src/Ombi/ClientApp/src/app/landingpage/landingpage.component.scss
src/Ombi/ClientApp/src/app/landingpage/landingpage.component.ts
src/Ombi/ClientApp/src/app/login/login.component.html
src/Ombi/ClientApp/src/app/login/login.component.scss
src/Ombi/ClientApp/src/app/login/login.component.ts
src/Ombi/ClientApp/src/app/login/resetpassword.component.html
src/Ombi/ClientApp/src/app/login/resetpassword.component.ts
src/Ombi/ClientApp/src/app/login/tokenresetpassword.component.html
src/Ombi/ClientApp/src/app/login/tokenresetpassword.component.ts
src/Ombi/ClientApp/src/app/services/image.service.ts
src/Ombi/Controllers/V1/ImagesController.cs

We now include the poster name on the background.

Landing and Login page improvements

---

src/Ombi/appsettings.json

In my case, Microsoft.EntityFrameworkCore.Query errors were silent in the file log which doesn't help troubleshooting.

Log Microsoft warnings to log file

---

src/Ombi.Api.Lidarr/Models/ArtistAdd.cs

When an artist is not found in Lidarr as part of requesting an album,
MusicSender will make a POST request against the /api/v1/artist endpoint
to add such artist.
Not all fields defined in ArtistAdd are initialized, and those
uninitialized will be `null` values in the JSON body of the request, as
shown in this intercepted request:
```
{
"addOptions": {
"AlbumsToMonitor": [
"e5c48b66-44ef-3685-ad53-45dbcd7294c0"
],
"monitor": 6,
"monitored": true,
"searchForMissingAlbums": false
},
"added": "2022-08-10T06:49:32.4374278+00:00",
"albumFolder": true,
"artistName": "Manolo García",
"cleanName": "manologarcía",
"disambiguation": null,
"discogsId": 0,
"ended": false,
"foreignArtistId": "1c8309da-9789-40bf-b9c2-e20064263820",
"images": [],
"links": [],
"metadataProfileId": 1,
"monitored": true, …
```

Ombi.Api.Lidarr: Remove unused fields from ArtistAdd

---

src/Ombi.Api.Plex/Models/Metadata.cs

Finally solved side-effect of https://github.com/Ombi-app/Ombi/pull/4652 and https://github.com/Ombi-app/Ombi/commit/ab1a11af78efbe9d37bd55aa80a640796c138a98 's quick fix.
Plex sync tested and working.
Fixes https://github.com/Ombi-app/Ombi/issues/4720

Fix conflicting property name for Swagger

---

src/Ombi.Api.Webhook/WebhookApi.cs

At the moment it is impossible to use a webhook pointing to an endpoint without Ombi adding a trailing `/` at the end of the URL. This PR removes the feature that let Ombi automatically add the trailing `/` at the end of the webhook URL.
This will break existing setups that rely on Ombi to add an expected trailing `/` but without this, other setups cannot use webhooks where the endpoint expects no trailing `/`.

Remove added trailing slash from webhook URL

---

src/Ombi.Schedule/Jobs/ArrAvailabilityChecker.cs
src/Ombi.Schedule/Jobs/AvailabilityChecker.cs
src/Ombi.Schedule/Jobs/Emby/EmbyAvaliabilityChecker.cs
src/Ombi.Schedule/Jobs/Jellyfin/JellyfinAvaliabilityChecker.cs
src/Ombi.Schedule/Jobs/Plex/PlexAvailabilityChecker.cs
src/Ombi.Store/Entities/IMediaServerContent.cs
src/Ombi.Store/Entities/SonarrEpisodeCache.cs

Follow-up of https://github.com/Ombi-app/Ombi/pull/4751 discussion

Encapsulate common TV availability checker logic

---

src/Ombi.Schedule/Processor/ChangeLogProcessor.cs

* Use .NET Version class to compare the versions, and only show update as available when version is greater

New version available even just upgraded to the last one (#4719)

---

src/Ombi.Schedule.Tests/PlexUserImporterTests.cs
src/Ombi.Schedule/Jobs/Plex/PlexUserImporter.cs
src/Ombi.Settings/Settings/Models/UserManagementSettings.cs
src/Ombi/ClientApp/src/app/interfaces/ISettings.ts
src/Ombi/ClientApp/src/app/settings/usermanagement/usermanagement.component.html

* Add opt-in feature to delete users that no longer exist in Plex when configured for Import Plex Users or Import Plex Admin

Provide a flag for missing users on Plex Server (#4688)

---

src/Ombi/ClientApp/src/app/settings/emby/emby.component.html
src/Ombi/ClientApp/src/app/settings/emby/emby.component.ts
src/Ombi/ClientApp/src/app/settings/jellyfin/jellyfin.component.html
src/Ombi/ClientApp/src/app/settings/jellyfin/jellyfin.component.ts

* Added the dirty toggle when server options are removed or disabled for Emby or Jellyfin
* It appears that the toggle was added for the Enable button in https://github.com/Ombi-app/Ombi/pull/3776, and then removed in https://github.com/Ombi-app/Ombi/pull/4252, but not sure if that was intentional.

Unable to Delete Jellyfin Server (#4705)

---

src/Ombi/ClientApp/src/app/discover/components/card/discover-card.component.ts
src/Ombi/ClientApp/src/app/discover/components/collections/discover-collections.component.html

Fixes an issue with loading flag getting stuck in true state in the following cases:
- Admin closes dialog without submitting the request.
- Request fails due to network or internal error.

Consistently reset loading flag when requesting movies on discover page.

---

src/Ombi/appsettings.json

This will remove warnings that are only meant for developers and are misleading for users.

Only log error messages from Microsoft

---

src/Ombi.Notifications/Agents/MobileNotification.cs

fix(notifications): Fixed the Partially TV notifications going to the admin #4797

fix(notifications): Fixed the Partially TV notifications going to the admin #4797

---

src/Ombi.Settings/Settings/Models/AuthenticationSettings.cs
src/Ombi/ClientApp/src/app/interfaces/ISettings.ts
src/Ombi/ClientApp/src/app/settings/authentication/authentication.component.html
src/Ombi/ClientApp/src/app/settings/authentication/authentication.component.scss
src/Ombi/ClientApp/src/app/settings/authentication/authentication.component.ts
src/Ombi/Controllers/V1/TokenController.cs

Since I manage my users externally using authentik, manually adding every user to Ombi is not feasable for me.
This PR adds a toggle to the authentication settings, and if enabled, a new user will be created if no existing user can be found when header authentication is being used. The default user settings defined in the User Management tab (roles, request limit, streaming country) will be applied.

Add the option for header authentication to create users

---

src/Ombi.Settings/Settings/Models/JobSettingsHelper.cs
src/Ombi/Controllers/V1/SettingsController.cs

The cron job can't be created if the year is more than 100 years in the future.
Getting the next valid time will return null if this is the case.
* add next-date cron validation to API
* Prevents Ombi from crashing on startup by changing to default CRON expression
* add next-date cron validation to the job settings page
*  Prevents the user from inputting a CRON job that won't trigger within 100 years
https://user-images.githubusercontent.com/15078358/232146846-80c8f416-da1a-4189-9621-2c3a3c537cdd.mov
Closes #4842

Fix Cron Validation (#4842)

---

src/Ombi/ClientApp/src/app/requests-list/components/movies-grid/movies-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.html

This pull request fixes a bug where the ApiAlias was not being displayed in the Ombi request list, even though it was included in the API request. The bug was caused by a missing piece of code in the section responsible for generating the request list.
This is the documentation that explain the use of ApiAlias: https://docs.ombi.app/info/api-information/#api-key 
To fix the bug, I added logic to the request list generation code to check for the presence of the ApiAlias header in API requests, and to include it in the request list when it is present. If the ApiAlias is not set(null) the old value of userAlias is used. This won't impact user that aren't using ApiAlias but will add a very useful feature for users that do.
This image show the changes. Test cases:
1. Where it shows phil, this …

Fix bug preventing ApiAlias header from appearing in Ombi request list

---

src/Ombi.Notifications/NotificationMessageCurlys.cs

RequestedByAlias field was missing from the notification message. I was trying to use it part of the webhooks and realized it was missing. 
In the following test I used the web UI to send the request so RequestedByAlias is null:
In the following test I sent the request using the API and set a value for RequestedByAlias in the request header, so RequestedByAlias is not null:
I placed it right after alias but could move it anywhere if needed.

Add the RequestedByAlias field to the Notification Message

---

src/Ombi.Core/Engine/MovieRequestEngine.cs
src/Ombi.Core/Engine/TvRequestEngine.cs

This is a fix for a bug I found with the RequestOnBehalf. https://github.com/Ombi-app/Ombi/issues/4915
Issue 4915 - Can't request on behalf with the API. 
Username.Equals("API", StringComparison.CurrentCultureIgnoreCase) is used in BaseEngine so I figured it's probably the best way to check for API unless a special role is created in OmbiRoles. I tried to keep the changes as minimal as possible but could rework this if needed.
This only works if requestOnBehalf value is a valid user Id or the API user id. This fix mirrors the behavior of the UI where you also need to select an existing user.

Bugfix: Allow RequestOnBehalf if requested from the API

---

src/Ombi.Schedule/Jobs/Emby/EmbyLibrarySync.cs

It seems that context.JobDetail.JobDataMap does not contain any data when the job is triggered manually by the content sync.
This resulted in the Played sync always running a full sync instead of a recently played sync.

Fix Emby played sync running a full sync during recently added sync

---

src/Ombi.Api.Emby/EmbyApi.cs
src/Ombi.Api.Emby/IBaseEmbyApi.cs
src/Ombi.Core/Authentication/OmbiUserManager.cs
src/Ombi/Controllers/BaseController.cs
src/Ombi/Controllers/V1/IdentityController.cs
src/Ombi/Controllers/V1/TokenController.cs

Show end-user external IP address to Emby when logging in as an Emby user

---

src/Ombi.Api.Emby/EmbyApi.cs
src/Ombi.Api.Emby/IBaseEmbyApi.cs
src/Ombi.Core/Engine/TvRequestEngine.cs
src/Ombi.DependencyInjection/IocExtensions.cs
src/Ombi.Schedule/Jobs/Emby/EmbyPlayedSync.cs
src/Ombi.Schedule/Jobs/Ombi/MediaDatabaseRefresh.cs
src/Ombi.Store/Context/ExternalContext.cs
src/Ombi.Store/Entities/Requests/ChildRequests.cs
src/Ombi.Store/Entities/UserPlayedEpisode.cs
src/Ombi.Store/Migrations/ExternalMySql/20230515182204_MovieEpisodePlayed.Designer.cs
src/Ombi.Store/Migrations/ExternalMySql/20230515182204_MovieEpisodePlayed.cs
src/Ombi.Store/Migrations/ExternalSqlite/20230515161757_EpisodeUserPlayed.Designer.cs
src/Ombi.Store/Migrations/ExternalSqlite/20230515161757_EpisodeUserPlayed.cs
src/Ombi.Store/Migrations/ExternalSqlite/ExternalSqliteContextModelSnapshot.cs
src/Ombi.Store/Repository/IUserPlayedEpisodeRepository.cs
src/Ombi.Store/Repository/UserPlayedEpisodeRepository.cs
src/Ombi/ClientApp/src/app/app.module.ts
src/Ombi/ClientApp/src/app/interfaces/IRequestModel.ts
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.html
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.scss
src/Ombi/ClientApp/src/app/requests-list/components/tv-grid/tv-grid.component.ts
src/Ombi/ClientApp/src/app/shared/shared.module.ts
src/Ombi/wwwroot/translations/en.json

This is the TV equivalent of https://github.com/Ombi-app/Ombi/pull/4881
A tooltip on the column header explains its meaning:
I'm curious to know if there's a more elegant way to do what I did in src/Ombi.Core/Engine/TvRequestEngine.cs, I'm not sure I'm using the most of C# capabilities here.
Once this PR is merged, I'm planning to work on bringing these features to Jellyfin and Plex sync.

Sync episodes played states from Emby

---

src/Ombi.Core.Tests/Rule/Request/AutoApproveRuleTests.cs
src/Ombi.Core.Tests/Rule/Request/CanRequestRuleTests.cs
src/Ombi.Core/Rule/Rules/Request/AutoApproveRule.cs
src/Ombi.Core/Rule/Rules/Request/CanRequestRule.cs
src/Ombi.Helpers/OmbiRoles.cs
src/Ombi.Store/Migrations/OmbiMySql/20230714081242_Approve4KMovie.Designer.cs
src/Ombi.Store/Migrations/OmbiMySql/20230714081242_Approve4KMovie.cs
src/Ombi.Store/Migrations/OmbiMySql/OmbiMySqlContextModelSnapshot.cs
src/Ombi.Store/Migrations/OmbiSqlite/20230714081017_Approve4KMovie.Designer.cs
src/Ombi.Store/Migrations/OmbiSqlite/20230714081017_Approve4KMovie.cs
src/Ombi/ClientApp/src/app/usermanagement/usermanagement-user.component.ts
src/Ombi/Controllers/V1/IdentityController.cs

Legacy "Auto Approve" role now only applies to non-4K requests 
Fixes #4957

feat: Add Auto Approve 4K role

---

src/Ombi.Core/Engine/V2/MovieSearchEngineV2.cs
src/Ombi.Core/Engine/V2/TvSearchEngineV2.cs
src/Ombi.Settings/Settings/Models/FeatureSettings.cs

#4624 brought a new algorithm to populate the Trending section on the Discover page. We've had no major negative feedback on the new algorithm since then.
It was still possible to use the old way the Trending section was populated. This decommissions the toggle that allowed it.

Remove old trending source

---

src/Ombi.Notifications.Templates/INewsletterTemplate.cs
src/Ombi.Notifications.Templates/NewsletterTemplate.cs
src/Ombi.Notifications.Templates/Templates/NewsletterTemplate.html
src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs

Makes changes to the newsletter to turn the logo image into a hyperlink to the application.
Requires that the _application url_ field is filled set in Settings/Customization. If the field is not set, the generated hyperlink will be self-referencing.

Linkify logo in newsletter

---

src/Ombi/ClientApp/src/app/settings/plex/components/plex-server-dialog/plex-server-dialog.component.html

I have observed an issue where certain password/form-fill managers will automatically fill in old plex server details (such as authentication token or machine identifier). For example, my lastpass seems to be remembering an old authentication token, and without my noticing will auto-fill in those details even when I haven't explicitly told it to. I imagine this happens with other password managers, and I don't see a particular need to autocomplete/auto-fill these details.
I have confirmed that the `autocomplete="off"` is an industry standard for inputs and modern managers will respect it (optionally). 
Switching to a different browser without lastpass, I have no issues. This might be a Chrome issue, but I don't see any data in my auto-fill settings where this data is being kept. Either …

Disable Autocomplete for Plex Server Dialog

---

src/Ombi/ClientApp/src/app/landingpage/landingpage.component.html
src/Ombi/ClientApp/src/app/landingpage/landingpage.component.scss

Update landingpage.component.html To Page Scrolling on mobile devices.
This is to address issue:
https://github.com/Ombi-app/Ombi/issues/5046
Tested on my mobile with success.

Update landingpage.component.html To Page Scrolling.

---

index.html

Fixes #5103
- Fix retrieves typo
- Use "Market with App Store" badge ([official from Apple](https://toolbox.marketingtools.apple.com/en-us/app-store/us/app/1335260043))

fix: retrieves typo and use "Market with App Store" badge

---

src/.idea/.idea.Ombi/.idea/indexLayout.xml
src/.idea/.idea.Ombi/.idea/workspace.xml
src/Ombi.Core/Helpers/DatabaseConfigurationSetup.cs
src/Ombi.Core/Helpers/FileSystem.cs
src/Ombi.Core/Helpers/IFileSystem.cs
src/Ombi.Core/Models/DatabaseConfiguration.cs
src/Ombi.Core/Services/DatabaseConfigurationService.cs
src/Ombi.Core/Services/IDatabaseConfigurationService.cs
src/Ombi.DependencyInjection/IocExtensions.cs
src/Ombi/ClientApp/src/app/wizard/database/database.component.html
src/Ombi/ClientApp/src/app/wizard/database/database.component.ts
src/Ombi/ClientApp/src/app/wizard/models/DatabaseSettings.ts
src/Ombi/ClientApp/src/app/wizard/services/wizard.service.ts
src/Ombi/ClientApp/src/app/wizard/welcome/welcome.component.html
src/Ombi/ClientApp/src/app/wizard/welcome/welcome.component.scss
src/Ombi/ClientApp/src/app/wizard/welcome/welcome.component.ts
src/Ombi/ClientApp/src/app/wizard/wizard.module.ts
src/Ombi/Controllers/V2/WizardController.cs
src/Ombi/Extensions/DatabaseExtensions.cs
src/Ombi/Models/V2/WizardDatabaseConfiguration.cs
src/Ombi/Ombi.csproj
tests/cypress/features/01-wizard/wizard.ts
tests/cypress/fixtures/api/v1/tv-search-extra-info.json
tests/cypress/integration/page-objects/wizard/wizard.page.ts

feat(wizard): :sparkles: Added the ability to start with a different database
